export const data=[{
    id:1,
    srcimg:"/image/furoda/27228d62-b441-450b-9ede-3c759c773eef.jpg",
    title:"Paket Haji Furoda",
    content:"Haji Furoda adalah program haji non kuota yang legal dan terdaftar dalam kuota haji pemerintah Arab Saudi, dan dilaporkan secara resmi ke Kementerian Haji Indonesia",
    contact:"",
    url:"/paket-tour/haji-furoda",
},
{
    id:1,
    srcimg:"https://akhirtahun.umrohhajisekeluarga.com/static/media/rtw01.46ee163fc006d3ad19b2.jpg",
    title:"Paket Umroh Desember 2023",
    content:"Kenapa Haji Khusus ,karena waktu tunggu Haji Khusus relatif lebih singkat dibandingkan dengan Haji Reguler. Waktu tunggu sekitar 5 sampai 6 tahun.",
    contact:"",
    url:"https://akhirtahun.umrohhajisekeluarga.com/",
},
{
    id:1,
    srcimg:"https://januari.umrohhajisekeluarga.com/static/media/compressing-df.8639aacab76e29cd53b2.jpg",
    title:"Paket Umroh Januari 2024",
    content:"Kenapa Haji Khusus ,karena waktu tunggu Haji Khusus relatif lebih singkat dibandingkan dengan Haji Reguler. Waktu tunggu sekitar 5 sampai 6 tahun.",
    contact:"",
    url:"https://januari.umrohhajisekeluarga.com",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh Februari 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh Maret 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh April 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh Mei 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh Juni 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh Juli 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh Agustus 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh September 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh Oktober 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh November 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},
{
    id:1,
    srcimg:"/image/coming_soon.png",
    title:"Paket Umroh Desember 2024",
    content:"Paket Umroh terdiri dari Umroh Reguler dan Umroh Plus Turki, yang mencakup perjalanan umroh standar serta tambahan wisata ke Turki setelah umroh selesai",
    contact:"",
    url:"/paket-tour/umroh",
},

]